name: Daily Scraper Email

on:
  schedule:
    - cron: '0 14 * * *'   # 12 PM UTC = 8 AM EST
  workflow_dispatch:       # Allows manual trigger too

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Upload debug HTML
      uses: actions/upload-artifact@v4
      with:
        name: timeout-html
        path: debug_timeout.html    

    - name: Run your script
      env:
        EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python scrap.py

 

